name: Update Matches

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Update Scripts Sequentially
        env:
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/google-chrome-stable'
          DEBUG: puppeteer:*
        run: |
          node ./scripts/icsToJson.js &&
          node ./scripts/pastEventFiltering.js &&
          node ./scripts/findPastEvents.js &&
          node ./scripts/updatePastEvents.js &&
          node ./scripts/updateLast10Matches.js &&
          node ./scripts/fetchUpcomingMatches.js &&
          node ./scripts/mergeJsonFiles.js jsons/pastEvents.json jsons/futureMatches.json jsons/mergedData.json &&
          node ./scripts/jsonToIcs.js

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m 'Update matches'
          git push
        continue-on-error: true
