name: Update Matches

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Convert ICS to JSON
        run: node ./scripts/icsToJson.js

      - name: Filter Past Events
        run: node ./scripts/pastEventFiltering.js

      - name: Find Past Events
        run: node ./scripts/findPastEvents.js

      - name: Update Past Events
        run: node ./scripts/updatePastEvents.js

      - name: Run Puppeteer Script for Last 10 Matches
        env:
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/google-chrome-stable'
          DEBUG: puppeteer:*
        run: node ./scripts/updateLast10Matches.js

      - name: Fetch Upcoming Matches
        run: node ./scripts/fetchUpcomingMatches.js

      - name: Merge JSON Files
        run: |
          node ./scripts/mergeJsonFiles.js ./jsons/pastEvents.json ./jsons/futureMatches.json jsons/mergedData.json

      - name: Convert JSON to ICS
        run: node ./scripts/jsonToIcs.js

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m 'Update matches'
          git push
        continue-on-error: true
